name: igufu32607
channels:
  - conda-forge
dependencies:
  - python==3.8
  - Cython
  - SimPEG==0.17.0
  - geoana==0.1.2
  - nbgitpuller
  - numpy==1.19.2
  - scipy==1.5.2
  - matplotlib==3.3.2
  - cartopy==0.19.0.post1
  - pandas==1.2.3
